export const REGIONS = [
  { code: '01', nom: 'Guadeloupe' },
  { code: '02', nom: 'Martinique' },
  { code: '03', nom: 'Guyane' },
  { code: '04', nom: 'La Réunion' },
  { code: '06', nom: 'Mayotte' },
  { code: '11', nom: 'Île-de-France' },
  { code: '24', nom: 'Centre-Val de Loire' },
  { code: '27', nom: 'Bourgogne-Franche-Comté' },
  { code: '28', nom: 'Normandie' },
  { code: '32', nom: 'Hauts-de-France' },
  { code: '44', nom: 'Grand Est' },
  { code: '52', nom: 'Pays de la Loire' },
  { code: '53', nom: 'Bretagne' },
  { code: '75', nom: 'Nouvelle-Aquitaine' },
  { code: '76', nom: 'Occitanie' },
  { code: '84', nom: 'Auvergne-Rhône-Alpes' },
  { code: '93', nom: 'Provence-Alpes-Côte d\'Azur' },
  { code: '94', nom: 'Corse' },
];

export const DEPARTEMENTS = [
  { code: '01', nom: 'Ain', region: '84' },
  { code: '02', nom: 'Aisne', region: '32' },
  { code: '03', nom: 'Allier', region: '84' },
  { code: '04', nom: 'Alpes-de-Haute-Provence', region: '93' },
  { code: '05', nom: 'Hautes-Alpes', region: '93' },
  { code: '06', nom: 'Alpes-Maritimes', region: '93' },
  { code: '07', nom: 'Ardèche', region: '84' },
  { code: '08', nom: 'Ardennes', region: '44' },
  { code: '09', nom: 'Ariège', region: '76' },
  { code: '10', nom: 'Aube', region: '44' },
  { code: '11', nom: 'Aude', region: '76' },
  { code: '12', nom: 'Aveyron', region: '76' },
  { code: '13', nom: 'Bouches-du-Rhône', region: '93' },
  { code: '14', nom: 'Calvados', region: '28' },
  { code: '15', nom: 'Cantal', region: '84' },
  { code: '16', nom: 'Charente', region: '75' },
  { code: '17', nom: 'Charente-Maritime', region: '75' },
  { code: '18', nom: 'Cher', region: '24' },
  { code: '19', nom: 'Corrèze', region: '75' },
  { code: '2A', nom: 'Corse-du-Sud', region: '94' },
  { code: '2B', nom: 'Haute-Corse', region: '94' },
  { code: '21', nom: 'Côte-d\'Or', region: '27' },
  { code: '22', nom: 'Côtes-d\'Armor', region: '53' },
  { code: '23', nom: 'Creuse', region: '75' },
  { code: '24', nom: 'Dordogne', region: '75' },
  { code: '25', nom: 'Doubs', region: '27' },
  { code: '26', nom: 'Drôme', region: '84' },
  { code: '27', nom: 'Eure', region: '28' },
  { code: '28', nom: 'Eure-et-Loir', region: '24' },
  { code: '29', nom: 'Finistère', region: '53' },
  { code: '30', nom: 'Gard', region: '76' },
  { code: '31', nom: 'Haute-Garonne', region: '76' },
  { code: '32', nom: 'Gers', region: '76' },
  { code: '33', nom: 'Gironde', region: '75' },
  { code: '34', nom: 'Hérault', region: '76' },
  { code: '35', nom: 'Ille-et-Vilaine', region: '53' },
  { code: '36', nom: 'Indre', region: '24' },
  { code: '37', nom: 'Indre-et-Loire', region: '24' },
  { code: '38', nom: 'Isère', region: '84' },
  { code: '39', nom: 'Jura', region: '27' },
  { code: '40', nom: 'Landes', region: '75' },
  { code: '41', nom: 'Loir-et-Cher', region: '24' },
  { code: '42', nom: 'Loire', region: '84' },
  { code: '43', nom: 'Haute-Loire', region: '84' },
  { code: '44', nom: 'Loire-Atlantique', region: '52' },
  { code: '45', nom: 'Loiret', region: '24' },
  { code: '46', nom: 'Lot', region: '76' },
  { code: '47', nom: 'Lot-et-Garonne', region: '75' },
  { code: '48', nom: 'Lozère', region: '76' },
  { code: '49', nom: 'Maine-et-Loire', region: '52' },
  { code: '50', nom: 'Manche', region: '28' },
  { code: '51', nom: 'Marne', region: '44' },
  { code: '52', nom: 'Haute-Marne', region: '44' },
  { code: '53', nom: 'Mayenne', region: '52' },
  { code: '54', nom: 'Meurthe-et-Moselle', region: '44' },
  { code: '55', nom: 'Meuse', region: '44' },
  { code: '56', nom: 'Morbihan', region: '53' },
  { code: '57', nom: 'Moselle', region: '44' },
  { code: '58', nom: 'Nièvre', region: '27' },
  { code: '59', nom: 'Nord', region: '32' },
  { code: '60', nom: 'Oise', region: '32' },
  { code: '61', nom: 'Orne', region: '28' },
  { code: '62', nom: 'Pas-de-Calais', region: '32' },
  { code: '63', nom: 'Puy-de-Dôme', region: '84' },
  { code: '64', nom: 'Pyrénées-Atlantiques', region: '75' },
  { code: '65', nom: 'Hautes-Pyrénées', region: '76' },
  { code: '66', nom: 'Pyrénées-Orientales', region: '76' },
  { code: '67', nom: 'Bas-Rhin', region: '44' },
  { code: '68', nom: 'Haut-Rhin', region: '44' },
  { code: '69', nom: 'Rhône', region: '84' },
  { code: '70', nom: 'Haute-Saône', region: '27' },
  { code: '71', nom: 'Saône-et-Loire', region: '27' },
  { code: '72', nom: 'Sarthe', region: '52' },
  { code: '73', nom: 'Savoie', region: '84' },
  { code: '74', nom: 'Haute-Savoie', region: '84' },
  { code: '75', nom: 'Paris', region: '11' },
  { code: '76', nom: 'Seine-Maritime', region: '28' },
  { code: '77', nom: 'Seine-et-Marne', region: '11' },
  { code: '78', nom: 'Yvelines', region: '11' },
  { code: '79', nom: 'Deux-Sèvres', region: '75' },
  { code: '80', nom: 'Somme', region: '32' },
  { code: '81', nom: 'Tarn', region: '76' },
  { code: '82', nom: 'Tarn-et-Garonne', region: '76' },
  { code: '83', nom: 'Var', region: '93' },
  { code: '84', nom: 'Vaucluse', region: '93' },
  { code: '85', nom: 'Vendée', region: '52' },
  { code: '86', nom: 'Vienne', region: '75' },
  { code: '87', nom: 'Haute-Vienne', region: '75' },
  { code: '88', nom: 'Vosges', region: '44' },
  { code: '89', nom: 'Yonne', region: '27' },
  { code: '90', nom: 'Territoire de Belfort', region: '27' },
  { code: '91', nom: 'Essonne', region: '11' },
  { code: '92', nom: 'Hauts-de-Seine', region: '11' },
  { code: '93', nom: 'Seine-Saint-Denis', region: '11' },
  { code: '94', nom: 'Val-de-Marne', region: '11' },
  { code: '95', nom: "Val-d'Oise", region: '11' },
  { code: '971', nom: 'Guadeloupe', region: '01' },
  { code: '972', nom: 'Martinique', region: '02' },
  { code: '973', nom: 'Guyane', region: '03' },
  { code: '974', nom: 'La Réunion', region: '04' },
  { code: '976', nom: 'Mayotte', region: '06' },
];

export const TRANCHES_EFFECTIFS = [
  { code: 'NN', label: '0 salarié (non déclaré)' },
  { code: '00', label: '0 salarié' },
  { code: '01', label: '1 – 2 salariés' },
  { code: '02', label: '3 – 5 salariés' },
  { code: '03', label: '6 – 9 salariés' },
  { code: '11', label: '10 – 19 salariés' },
  { code: '12', label: '20 – 49 salariés' },
  { code: '21', label: '50 – 99 salariés' },
  { code: '22', label: '100 – 199 salariés' },
  { code: '31', label: '200 – 249 salariés' },
  { code: '32', label: '250 – 499 salariés' },
  { code: '41', label: '500 – 999 salariés' },
  { code: '42', label: '1 000 – 1 999 salariés' },
  { code: '51', label: '2 000 – 4 999 salariés' },
  { code: '52', label: '5 000 – 9 999 salariés' },
  { code: '53', label: '10 000+ salariés' },
];

export const FORMES_JURIDIQUES = [
  { code: '1000', label: 'Entrepreneur individuel' },
  { code: '5498', label: 'SARL' },
  { code: '5499', label: 'EURL' },
  { code: '5308', label: 'SA' },
  { code: '5710', label: 'SAS' },
  { code: '5720', label: 'SASU' },
  { code: '6316', label: 'Société civile' },
  { code: '6540', label: 'SCM (Sté Civile de Moyens)' },
  { code: '6552', label: 'Société civile professionnelle' },
  { code: '9210', label: 'Association loi 1901' },
];

export const CA_TRANCHES = [
  { label: '< 200 k€',      min: undefined,   max: 200_000 },
  { label: '200 – 500 k€',  min: 200_000,     max: 500_000 },
  { label: '500 k€ – 1 M€', min: 500_000,     max: 1_000_000 },
  { label: '1 – 2 M€',      min: 1_000_000,   max: 2_000_000 },
  { label: '2 – 5 M€',      min: 2_000_000,   max: 5_000_000 },
  { label: '5 – 10 M€',     min: 5_000_000,   max: 10_000_000 },
  { label: '10 – 20 M€',    min: 10_000_000,  max: 20_000_000 },
  { label: '> 20 M€',       min: 20_000_000,  max: undefined },
];

const Y = new Date().getFullYear();

// AGE_PRESETS → converted to birth date ranges for the API
// API param: date_naissance_personne_min / date_naissance_personne_max
export const AGE_PRESETS = [
  { label: '< 40 ans',    dobMin: `${Y - 39}-01-01`, dobMax: undefined },
  { label: '40 – 50 ans', dobMin: `${Y - 50}-01-01`, dobMax: `${Y - 40}-12-31` },
  { label: '50 – 60 ans', dobMin: `${Y - 60}-01-01`, dobMax: `${Y - 50}-12-31` },
  { label: '50+ ans ★',   dobMin: undefined,          dobMax: `${Y - 50}-12-31` },
  { label: '60 – 70 ans', dobMin: `${Y - 70}-01-01`, dobMax: `${Y - 60}-12-31` },
  { label: '60+ ans',     dobMin: undefined,          dobMax: `${Y - 60}-12-31` },
  { label: '> 70 ans',    dobMin: undefined,          dobMax: `${Y - 70}-12-31` },
];

export const KEYWORD_PRESETS = [
  { label: 'Expert-comptable', value: 'expert comptable' },
];

export const APE_OPTIONS = [
  { code: '69.20Z', label: '69.20Z — Activités comptables' },
  { code: '69.10Z', label: '69.10Z — Activités juridiques' },
  { code: '70.22Z', label: '70.22Z — Conseil aux entreprises' },
  { code: '74.90B', label: '74.90B — Autres activités conseil' },
];

export const TRANCHE_LABEL: Record<string, string> = Object.fromEntries(
  TRANCHES_EFFECTIFS.map(t => [t.code, t.label])
);
